### ISSUE TITLE
Need to update this package to work with int_date v 0.20

### ISSUE THREAD

**Issue by tempest-noob** [jealous/stockstats#107]
from stockstats import StockDataFrame not working due to update of int_date package.

**Comment by jealous** [comment]
Thanks for the info.  I will update a new version to remove this dependency ASAP.

**Comment by T-Berger** [comment]
Hi Cedric,
I still get the ImportError on python3.7

```
/usr/local/lib/python3.7/dist-packages/stockstats.py in <module>()
     35 import numpy as np
     36 import pandas as pd
---> 37 from int_date import get_date_from_diff
     38 
     39 __author__ = 'Cedric Zhuang'

ImportError: cannot import name 'get_date_from_diff' from 'int_date' (/usr/local/lib/python3.7/dist-packages/int_date.py)
```

**Comment by jealous** [comment]
Please use the latest 0.4.0 release which removes the dependency of `int_date`.
